"""Initial migration

Revision ID: 807046b73df0
Revises:
Create Date: 2026-08-02 13:52:12.341547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "807046b73df0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "MAIN_DISH",
                "SIDE_DISH",
                "SOUP",
                "RICE",
                "NOODLE",
                "DESSERT",
                "OTHER",
                name="recipecategory",
            ),
            nullable=False,
        ),
        sa.Column("ingredients", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("cooking_time_minutes", sa.String(), nullable=True),
        sa.Column("servings", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("is_public", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
    )
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recipes_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_recipes_title"), ["title"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "children",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_children_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_children")),
    )
    with op.batch_alter_table("children", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_children_user_id"), ["user_id"], unique=False)

    op.create_table(
        "allergies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_allergies_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allergies")),
    )
    with op.batch_alter_table("allergies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_allergies_child_id"), ["child_id"], unique=False)

    op.create_table(
        "preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
            name=op.f("fk_preferences_child_id_children"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferences")),
    )
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_preferences_child_id"), ["child_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_preferences_child_id"))

    op.drop_table("preferences")
    with op.batch_alter_table("allergies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allergies_child_id"))

    op.drop_table("allergies")
    with op.batch_alter_table("children", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_children_user_id"))

    op.drop_table("children")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipes_title"))
        batch_op.drop_index(batch_op.f("ix_recipes_category"))

    op.drop_table("recipes")
    # ### end Alembic commands ###
